// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwEW_5WZzGi_hM61QMWBqInODUx3ysMow',
    appId: '1:1031518825779:web:879524bc3e94052de86246',
    messagingSenderId: '1031518825779',
    projectId: 'smartsumbong',
    authDomain: 'smartsumbong.firebaseapp.com',
    storageBucket: 'smartsumbong.firebasestorage.app',
    measurementId: 'G-5L5XXHYDX2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqPwasmsk5zXy29UIwUyE6QhNVPi9SxrQ',
    appId: '1:1031518825779:android:04c83db75ad160aae86246',
    messagingSenderId: '1031518825779',
    projectId: 'smartsumbong',
    storageBucket: 'smartsumbong.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDA3ZZh-EvHNVKn8TgEzwsxG2QbcpllQiw',
    appId: '1:1031518825779:ios:3c496b9ca32976e0e86246',
    messagingSenderId: '1031518825779',
    projectId: 'smartsumbong',
    storageBucket: 'smartsumbong.firebasestorage.app',
    iosBundleId: 'ph.smartsumbong.tanod',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDA3ZZh-EvHNVKn8TgEzwsxG2QbcpllQiw',
    appId: '1:1031518825779:ios:3c496b9ca32976e0e86246',
    messagingSenderId: '1031518825779',
    projectId: 'smartsumbong',
    storageBucket: 'smartsumbong.firebasestorage.app',
    iosBundleId: 'ph.smartsumbong.tanod',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwEW_5WZzGi_hM61QMWBqInODUx3ysMow',
    appId: '1:1031518825779:web:8c16f694cd822ce2e86246',
    messagingSenderId: '1031518825779',
    projectId: 'smartsumbong',
    authDomain: 'smartsumbong.firebaseapp.com',
    storageBucket: 'smartsumbong.firebasestorage.app',
    measurementId: 'G-YKZ48ZQDR1',
  );
}
