// SmartSumbong — tanod app entry point.
//
// Run with:
//   flutter run --dart-define-from-file=dart_defines.json
//
// The same four values as the resident app, pointing at the same
// project. All four are public by design: they ship inside any built
// APK and can be read out of it. RLS is what guards the data, and a
// tanod's JWT carries role 'tanod', which is what every dispatch policy
// keys off. The service role key must never appear here.

import 'dart:async';

import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:smartsumbong_core/smartsumbong_core.dart';
import 'package:supabase_flutter/supabase_flutter.dart';

// Generated by `flutterfire configure`, run once against this app's
// Android directory -- see the deploy notes. Nothing in this file
// compiles until that has been run at least once; this is expected, not
// a bug, and is the one manual step the app-code changes here cannot do
// for you (it needs your own Firebase login).
import 'firebase_options.dart';
import 'screens/edit_profile_screen.dart';
import 'screens/languages_screen.dart';
import 'screens/settings_screen.dart';
import 'screens/tanod_home_screen.dart';
import 'screens/notifications_screen.dart';
import 'screens/reports_screen.dart';
import 'screens/account_status_screen.dart';
import 'screens/change_password_screen.dart';
import 'screens/launch_gate.dart';
import 'screens/login_screen.dart';
import 'theme.dart';

const _supabaseUrl = String.fromEnvironment('SUPABASE_URL');
const _supabaseAnonKey = String.fromEnvironment('SUPABASE_ANON_KEY');
const _cloudName = String.fromEnvironment('CLOUDINARY_CLOUD_NAME');
const _uploadPreset = String.fromEnvironment('CLOUDINARY_UPLOAD_PRESET');

/// Lets a push notification tap navigate before any screen's own
/// BuildContext exists yet (a cold start from a killed state).
final navigatorKey = GlobalKey<NavigatorState>();

Future<void> main() async {
  // Wraps startup so an error thrown before or outside the widget tree
  // still reaches Crashlytics instead of vanishing into an unhandled
  // zone error.
  await runZonedGuarded(() async {
    WidgetsFlutterBinding.ensureInitialized();

    final missing = {
      'SUPABASE_URL': _supabaseUrl,
      'SUPABASE_ANON_KEY': _supabaseAnonKey,
      'CLOUDINARY_CLOUD_NAME': _cloudName,
      'CLOUDINARY_UPLOAD_PRESET': _uploadPreset,
    }.entries.where((e) => e.value.isEmpty).map((e) => e.key).toList();

    if (missing.isNotEmpty) {
      runApp(_ConfigError(missing));
      return;
    }

    await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
    CrashReporting.install();

    // Session tokens in the Android Keystore rather than plain
    // SharedPreferences -- see secure_session_storage.dart for why.
    await Supabase.initialize(
      url: _supabaseUrl,
      anonKey: _supabaseAnonKey,
      authOptions: FlutterAuthClientOptions(
        localStorage: SecureLocalStorage(),
      ),
    );

    // The tanod app has no single-dispatch route yet (dispatch_order is
    // opened from Home/Reports with a ticket object, not a named route
    // with an id argument), so a notification tap lands on the
    // notifications list rather than a specific ticket. Extending this
    // to jump straight to one dispatch is a reasonable fast-follow, not
    // done here.
    await PushNotifications.init(
      onOpenReport: (_) => navigatorKey.currentState?.pushNamed('/notifications'),
    );

    if (Supabase.instance.client.auth.currentUser != null) {
      await PushNotifications.registerToken();
    }
    Supabase.instance.client.auth.onAuthStateChange.listen((data) {
      final event = data.event;
      if (event == AuthChangeEvent.signedIn ||
          event == AuthChangeEvent.initialSession) {
        PushNotifications.registerToken();
      } else if (event == AuthChangeEvent.signedOut) {
        PushNotifications.unregisterToken();
      }
    });

    runApp(const SmartSumbongTanodApp());
  }, (error, stack) {
    CrashReporting.recordError(error, stack);
  });
}

class SmartSumbongTanodApp extends StatelessWidget {
  const SmartSumbongTanodApp({super.key});

  @override
  Widget build(BuildContext context) {
    final auth = AuthService(Supabase.instance.client);

    return MaterialApp(
      title: 'SmartSumbong Tanod',
      debugShowCheckedModeBanner: false,
      theme: buildTanodTheme(),
      navigatorKey: navigatorKey,
      builder: (context, child) =>
          ConnectivityBanner(child: child ?? const SizedBox.shrink()),
      initialRoute: '/',
      routes: {
        '/': (_) => LaunchGate(auth: auth),
        '/login': (_) => LoginScreen(auth: auth),
        // '/duty' is gone. Duty status lives on Home now, per
        // HOME - TANOD, so the launch gate lands here instead.
        '/home': (_) => TanodHomeScreen(auth: auth),
        '/reports': (_) => const ReportsScreen(),
        '/notifications': (_) => const NotificationsScreen(),
        '/settings': (_) => SettingsScreen(auth: auth),
        '/edit-profile': (_) => EditProfileScreen(auth: auth),
        '/languages': (_) => const LanguagesScreen(),
        '/change-password': (_) => ChangePasswordScreen(auth: auth),
        '/verification-pending': (_) =>
            const _Placeholder('Verification pending'),
        '/verification-rejected': (_) => AccountStatusScreen(
              auth: auth,
              block: AccountBlock.rejected,
              canRegisterAgain: false),
        '/account-suspended': (_) => AccountStatusScreen(
              auth: auth,
              block: AccountBlock.suspended,
              canRegisterAgain: false),
      },
    );
  }
}

class _Placeholder extends StatelessWidget {
  const _Placeholder(this.name);

  final String name;

  @override
  Widget build(BuildContext context) => Scaffold(
        body: Center(child: Text(name)),
      );
}

class _ConfigError extends StatelessWidget {
  const _ConfigError(this.missing);

  final List<String> missing;

  @override
  Widget build(BuildContext context) => MaterialApp(
        debugShowCheckedModeBanner: false,
        home: Scaffold(
          body: Padding(
            padding: const EdgeInsets.all(32),
            child: Center(
              child: Text(
                'Missing configuration:\n\n${missing.join('\n')}\n\n'
                'Run with --dart-define-from-file=dart_defines.json',
                textAlign: TextAlign.center,
              ),
            ),
          ),
        ),
      );
}
