#!/usr/bin/env bash
# Writes supabase/migrations/<N>_hazard_zones.sql from admin/assets/map/hazards.geojson
# (the NOAH flood and storm-surge map the portal draws), so the database can
# tell whether a report falls inside a hazard zone. Geometry is stored as
# TWKB at 5 decimals (about 1 m), which keeps the file near 100 KB.
#
# Needs the local test database left running:
#   KEEP_DB=1 bash supabase/tests/local/run-local.sh
#   bash supabase/tools/gen_hazard_zones.sh 0121
set -euo pipefail
n=${1:?migration number, e.g. 0121}
root=$(cd "$(dirname "$0")/../.." && pwd)
out="$root/supabase/migrations/${n}_hazard_zones.sql"
psql=(psql -h /var/tmp/smartsumbong-pg -p "${PGPORT_LOCAL:-55433}" -U postgres -X -qAt -v ON_ERROR_STOP=1)
tsv=$(mktemp)
python3 - "$root/admin/assets/map/hazards.geojson" > "$tsv" <<'PY'
import json, sys
for f in json.load(open(sys.argv[1]))["features"]:
    p = f["properties"]
    print(f'{p["hazard"]}\t{p["level"]}\t{json.dumps(f["geometry"])}')
PY
{
  cat <<HEAD
-- ${n}: NOAH hazard zones in the database (SMART prototype, 10 Oct 2026).
--
-- The same flood and storm-surge map the portal draws
-- (admin/assets/map/hazards.geojson), so smart_triage() can tell whether a
-- report lies inside one. Generated by supabase/tools/gen_hazard_zones.sh;
-- regenerate rather than edit. Geometry: TWKB, 5 decimals (about 1 m).

-- Stored in small pieces (at most 128 points each, ST_Subdivide), so the
-- index finds the one piece under a point instead of testing a whole
-- zone: about 0.1 ms per report instead of 30.
create table public.hazard_zones (
  id     integer generated always as identity primary key,
  hazard text     not null check (hazard in ('flood', 'surge')),
  level  smallint not null check (level between 1 and 3),
  geom   geometry(Polygon, 4326) not null
);
create index hazard_zones_geom_idx on public.hazard_zones using gist (geom);
alter table public.hazard_zones enable row level security;
create policy hazard_zones_read on public.hazard_zones for select using (true);
comment on table public.hazard_zones is
  '${n}: NOAH flood and storm-surge zones (level 1 low to 3 high), from the portal''s hazards.geojson.';

create temp table hazard_zones_src (hazard text, level smallint, geom geometry);
insert into hazard_zones_src (hazard, level, geom) values
HEAD
  "${psql[@]}" <<SQL
create temp table hz (hazard text, level int, gj text);
\copy hz from '$tsv'
select string_agg(format(E'(%L, %s, st_setsrid(st_geomfromtwkb(decode(%L, ''base64'')), 4326))',
                         hazard, level, translate(encode(st_astwkb(st_setsrid(st_geomfromgeojson(gj), 4326), 5), 'base64'), E'\n', '')),
                  E',\n' order by hazard, level) || ';'
  from hz;
SQL
  cat <<'TAIL'

insert into public.hazard_zones (hazard, level, geom)
select hazard, level, (st_dump(st_subdivide(st_makevalid(geom), 128))).geom
  from hazard_zones_src;
drop table hazard_zones_src;
TAIL
} > "$out"
rm -f "$tsv"
echo "wrote $out ($(wc -c < "$out") bytes)"
