# google_mlkit_text_recognition (via smartsumbong_core's on-device OCR
# triage, migration 0039) only ever uses the Latin recognizer in this
# app -- the per-script recognizer classes below are optional add-ons
# that aren't bundled, so R8 can't resolve them by static analysis even
# though TextRecognizer.initialize() never actually reaches those
# branches at runtime here. Rules as generated by the release build's
# own missing_rules.txt (14 Sep 2026).
-dontwarn com.google.mlkit.vision.text.chinese.ChineseTextRecognizerOptions$Builder
-dontwarn com.google.mlkit.vision.text.chinese.ChineseTextRecognizerOptions
-dontwarn com.google.mlkit.vision.text.devanagari.DevanagariTextRecognizerOptions$Builder
-dontwarn com.google.mlkit.vision.text.devanagari.DevanagariTextRecognizerOptions
-dontwarn com.google.mlkit.vision.text.japanese.JapaneseTextRecognizerOptions$Builder
-dontwarn com.google.mlkit.vision.text.japanese.JapaneseTextRecognizerOptions
-dontwarn com.google.mlkit.vision.text.korean.KoreanTextRecognizerOptions$Builder
-dontwarn com.google.mlkit.vision.text.korean.KoreanTextRecognizerOptions
